name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2023.2
        with:
          pr-mode: false
          args: --apply-fixes
          push-fixes: pull-request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
